### ISSUE TITLE
Where can I get MNEc_Ec2 

### ISSUE THREAD

**Issue by SichongP** [UMN-EGGL/MNEc2to3#1]
Hello,

I'm trying to replicate the workflow as well as to identify SNPs moved from chrUn to an autosome in new assembly. However, I am having trouble finding the MNEc_Ec2 assembly. Can you point me where I can get the fasta file for MNEc_Ec2.

Thanks

**Comment by schae234** [comment]
Hi @SichongP 
Ill track this down and get you a link to the Fasta File.

**Comment by schae234** [comment]
Hi @SichongP 
Sorry this took a while to track down. MNEc_Ec2 was a reference genome that we used to design the MNEc2 SNP chip. It contained the official EquCab2.0 references sequences as well as some additional contigs discovered from RNA-Seq that were not yet included in the reference genome. You can read more about the process we used to make the genome [here](https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-017-3943-8#Sec23).

You can find the raw FASTA file for the reference genome we used [here](http://schae234.s3.msi.umn.edu/MNEc_Ec2.tar.gz). Please let me know if you need anything else in regards to this.

**Comment by SichongP** [comment]
Thank you!
